apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  #where argcod pods are
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Bedier1/argocd
    targetRevision: master
    path: k8s
    directory:
      recurse:
  destination: 
    server: https://kubernetes.default.svc
    #https://192.168.49.2:8443
    namespace: myapp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
      FailOnSharedResource=true
      ApplyOutOfSyncOnly=true
      Replace=true
      #sync only changed files in git

    automated:
       #overide manuel edit
      selfHeal: true
      prune: true
