apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  #where argcod pods are
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Bedier1/argocd
    targetRevision: HEAD
    path: k8s
  destination: 
    server: https://kubernetes.default.svc
    #https://192.168.49.2:8443
    namespace: myapp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
       #overide manuel edit
      selfHeal: true
      prune: true
