apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
stringData:
  name: 
  server:
  config: |
  {
    "bearerToken":  ,
    "tlsCLientConfig": {
    "insecure": false,
     "caData": 
    } 
  }