apiVersion: v1
kind: Secret
metadata:
  name: local-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    env: "dev"
type: Opaque
stringData:
  name: local-cluster
  server: https://kubernetes.default.svc
  config: |
    {
      "tlsClientconfig": {
      "insecure": false
      }
    }
